//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBDVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int CarId { get; set; }
        public int EmpId { get; set; }
        public int CusId { get; set; }
        public string TypeWork { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
